"""Automate template/wiki release validation, commit, tag, push, and GitHub Release creation."""
import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent

STAGE_PATHS = [
    '.github/workflows/wiki-lint.yml',
    'AGENTS.md',
    'CHANGELOG.md',
    'README.md',
    'SETUP-GUIDE.md',
    'index.md',
    'starter-files',
    'templates',
    'ontology-templates',
    'scripts',
    'wiki',
    'graphify-out',
    'outputs/wiki-ops',
]


def python_files():
    return sorted(
        str(path.relative_to(ROOT))
        for path in (ROOT / 'scripts').glob('*.py')
    )


def validation_commands():
    commands = [[sys.executable, '-m', 'py_compile', *python_files()]]
    if (ROOT / 'wiki' / 'ontology').exists():
        commands.extend([
            [sys.executable, 'scripts/check-ontology.py'],
            [sys.executable, 'scripts/wiki-quality-gates.py'],
            [sys.executable, 'scripts/check-graph-hygiene.py'],
            [sys.executable, 'scripts/check-related-to-budget.py'],
        ])
    commands.append(['git', 'diff', '--check'])
    return commands


def run(command, dry_run=False):
    print('+ ' + ' '.join(command))
    if dry_run:
        return
    env = os.environ.copy()
    env['PYTHONDONTWRITEBYTECODE'] = '1'
    subprocess.run(command, cwd=ROOT, check=True, env=env)


def main():
    parser = argparse.ArgumentParser(description='Release wiki repository.')
    parser.add_argument('version', help='Version tag, e.g. v1.15.0')
    parser.add_argument('--message', default='', help='Commit/tag message')
    parser.add_argument('--push', action='store_true', help='Push main and tag')
    parser.add_argument('--github-release', action='store_true', help='Create GitHub Release with gh')
    parser.add_argument('--dry-run', action='store_true', help='Print commands only')
    args = parser.parse_args()
    message = args.message or f'{args.version}: release wiki updates'
    for command in validation_commands():
        run(command, args.dry_run)
    if (ROOT / 'outputs' / 'wiki-ops' / 'repo-metrics.json').exists():
        run([sys.executable, 'scripts/update-metrics-snippets.py'], args.dry_run)
    stage_paths = [path for path in STAGE_PATHS if (ROOT / path).exists()]
    run(['git', 'add', *stage_paths], args.dry_run)
    run(['git', 'commit', '-m', message], args.dry_run)
    run(['git', 'tag', '-a', args.version, '-m', message], args.dry_run)
    if args.push:
        run(['git', 'push', 'origin', 'main'], args.dry_run)
        run(['git', 'push', 'origin', args.version], args.dry_run)
    if args.github_release:
        notes = changelog_notes(args.version)
        run(['gh', 'release', 'create', args.version, '--title', message, '--notes', notes], args.dry_run)


def changelog_notes(version):
    changelog = ROOT / 'CHANGELOG.md'
    if not changelog.exists():
        return 'Generated by scripts/release-wiki.py'
    text = changelog.read_text(encoding='utf-8')
    heading = version.lstrip('v')
    marker = f'## [{heading}]'
    start = text.find(marker)
    if start < 0:
        return 'Generated by scripts/release-wiki.py'
    next_heading = text.find('\n## [', start + len(marker))
    section = text[start: next_heading if next_heading >= 0 else len(text)].strip()
    return section


if __name__ == '__main__':
    main()